### ISSUE TITLE
DATABASELAYOUT.sql not accurate

### ISSUE THREAD

**Issue by kirrus** [blind-coder/blindRSS#1]
DATABASELAYOUT needs an update, loading it into a clean database doesn't populate with the fields, leaving the program non-functional, and throwing fun SQL errors like
Error: Unknown column 'favicon' in 'field list'<br />SQL was:INSERT INTO feeds (startID, endID, cacheimages, unreadOnChange, name, url, favicon) VALUES (2, 2+1, 'yes', 'yes', 'Art.Gnome', 'http://art.gnome.org/backend.php', '')

(after I ran the 1.0 -> 1.1 update)

**Comment by blind-coder** [comment]
Fixed this in e5d9357..b0d6725
Thanks!
